version: '3'
services:
  db:
    container_name: hometime-db
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432'
  api:
    container_name: hometime-api
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - './api/:/api'
    ports:
      - '8000:3000'
    depends_on:
      - db
  app:
    container_name: hometime-app
    build: ./app
    command: yarn dev
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
