default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: hometime_dev
test:
  <<: *default
  database: hometime_test
production:
  <<: *default
  database: hometime_live
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
