default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: api
  username: hometime_postgres
  password: hometime_pass

development:
  <<: *default
  database: hometime_dev
test:
  <<: *default
  database: hometime_test
production:
  <<: *default
  database: hometime_live
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
